const TYPES = {
    CREATE_ANIMAL: "CREATE_ANIMAL",
    CREATE_ANIMAL_OK: "CREATE_ANIMAL_OK",
    CREATE_ANIMAL_ERROR: "CREATE_ANIMAL_ERROR",
    LOADING_ANIMALS: "LOADING_ANIMALS",
    LOADING_ANIMALS_OK: "LOADING_ANIMALS_OK",
    LOADING_ANIMALS_ERROR: "LOADING_ANIMALS_ERROR",
}

export default TYPES;